
spring:
  application:
    name: ZLinkSerVer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: Zzy.0613
    url: jdbc:mysql://49.232.80.153:3306/ZLinkdb?serverTimezone=UTC
    username: 'root'
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true